# Generated by Django 2.1.2 on 2020-08-07 17:15

import Home.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition_title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(default='img', max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to=Home.models.get_exhib_folder)),
            ],
        ),
        migrations.CreateModel(
            name='Function_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(default='img', max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to=Home.models.get_func_folder)),
            ],
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(default='img', max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to=Home.models.get_image_filename)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Project')),
            ],
        ),
        migrations.AddField(
            model_name='function_images',
            name='function_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Functions'),
        ),
        migrations.AddField(
            model_name='exhibition_images',
            name='exhibition_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Project'),
        ),
    ]
