# Generated by Django 2.1.2 on 2020-08-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition_images',
            name='exhibition_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Exhibition'),
        ),
    ]
