# Generated by Django 2.1.2 on 2020-08-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Bharat Bhakti Sansthan', max_length=200),
        ),
    ]
