# Generated by Django 2.1.2 on 2020-08-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200811_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Update',
        ),
    ]
