# Generated by Django 2.1.2 on 2020-08-11 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_delete_event_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 11, 10, 29, 34, 167391)),
        ),
    ]
