# Generated by Django 2.1.2 on 2020-08-11 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_event_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 11, 10, 30, 6, 200532)),
        ),
    ]
